# -*- coding: utf-8 -*-
"""
Admin: Rule Configuration — pending item #3 (F10 in the PRD: "View/adjust
the two trigger rule thresholds").

Not a form that silently saves a number: adjusting a threshold here runs a
live recomputation against the real transaction data first, so whoever is
changing R1/R2 can see roughly how many more (or fewer) accounts would
trigger before committing to it. The dataset's actual alerts table is never
regenerated by this screen — that stays fixed, so the frozen C1/C2 demo
scenario can never be altered by an admin fat-fingering a threshold.
"""
import os
import streamlit as st

import sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from data.runtime_db import get_rule_config, set_rule_param, get_audit_log
from data.trigger_rules import preview_trigger_counts
from ui_common import require_login, role_warning, page_banner

st.set_page_config(page_title="InvestigateIQ — Rule Config", page_icon="⚙️", layout="wide")
user_name, user_role = require_login()

ADMIN_PASSCODE = os.environ.get("ADMIN_PASSCODE", "investigateiq-admin")

page_banner("⚙️", "Admin — Trigger Rule Configuration", "Adjust R1/R2 thresholds and preview the real effect before saving.")
st.write("")
role_warning(user_role, "Admin")

if "rules_admin_unlocked" not in st.session_state:
    st.session_state.rules_admin_unlocked = False

if not st.session_state.rules_admin_unlocked:
    code = st.text_input(
        "Admin passcode", type="password",
        help="Prototype-level gate (not production security) — separates this screen from the "
             "regular investigator workspace, matching the mock-auth scope used throughout this build.",
    )
    if st.button("Unlock"):
        if code == ADMIN_PASSCODE:
            st.session_state.rules_admin_unlocked = True
            st.rerun()
        else:
            st.error("Incorrect passcode.")
    st.stop()

config = get_rule_config()

st.subheader("Current thresholds (saved)")
c1, c2, c3 = st.columns(3)
c1.metric("R1 — Amount deviation", f"{config[('R1','deviation_multiplier')]}x baseline",
          help="R1 fires when a credit is at least this many times the account's own trailing average — "
               "the first of the two rules behind the frozen C1/C2 demo scenario.")
c2.metric("R2 — Pass-through", f"{config[('R2','pass_through_pct')]}% of credit",
          help="R2 fires when at least this share of an R1-flagged credit leaves the account again within "
               "the window below — the 'rapid movement of funds' half of the pattern.")
c3.metric("R2 — Window", f"{config[('R2','window_hours')]} hours",
          help="How long after the flagged credit R2 keeps watching for it to leave again.")

st.divider()
st.subheader("Propose new thresholds")
st.caption(
    "These sliders don't save anything yet. Adjust, then **Preview impact** to see roughly how many accounts "
    "in the real dataset would trigger under the new settings — only then decide whether to save."
)

pc1, pc2, pc3 = st.columns(3)
new_dev = pc1.slider("R1: deviation multiplier", 2.0, 10.0, float(config[("R1", "deviation_multiplier")]), 0.5,
                      help="A credit must be at least this many times the account's trailing average to flag R1.")
new_pct = pc2.slider("R2: pass-through %", 30.0, 100.0, float(config[("R2", "pass_through_pct")]), 5.0,
                      help="This much of the flagged credit must leave again within the window to flag R2.")
new_window = pc3.slider("R2: window (hours)", 12.0, 168.0, float(config[("R2", "window_hours")]), 6.0,
                         help="How long after the credit R2 keeps watching for it to leave again.")

proposed = {("R1", "deviation_multiplier"): new_dev, ("R2", "pass_through_pct"): new_pct, ("R2", "window_hours"): new_window}
changed = proposed != {k: float(v) for k, v in config.items()}

if st.button("🔍 Preview impact on the real dataset", type="secondary",
             help="Recomputes R1/R2 against real (fictional) account transaction history using the sliders "
                  "above — read-only, nothing is saved by clicking this."):
    with st.spinner("Recomputing R1/R2 against real transaction history..."):
        result = preview_trigger_counts(proposed, sample_limit=300)
    st.session_state["rule_preview"] = result

if "rule_preview" in st.session_state:
    r = st.session_state["rule_preview"]
    st.markdown("**Preview result** (sample of up to 300 accounts, real transaction data):")
    pc1, pc2, pc3 = st.columns(3)
    pc1.metric("Accounts checked", r["accounts_checked"])
    pc2.metric("Would meet R1", r["r1_only_count"])
    pc3.metric("Would meet R1 + R2 (full alert)", r["r1_and_r2_count"])
    if r["examples"]:
        st.caption("Example accounts that would trigger both rules under these settings:")
        st.dataframe(r["examples"], hide_index=True, use_container_width=True)
    else:
        st.caption("No accounts in this sample would meet both rules under these settings.")

st.divider()
st.subheader("Save")
admin_name = st.text_input(
    "Your name (for the audit trail)", value=user_name,
    help="Every threshold change is written to the audit log below with this name attached — required, "
         "can't be blank.",
)
if st.button("💾 Save these thresholds", type="primary", disabled=not changed,
             help="Saves the sliders above as the new configured thresholds. Disabled until you change at "
                  "least one slider from its currently saved value. Does not touch the existing dataset's "
                  "41 alerts — see the scope note below."):
    if not admin_name.strip():
        st.error("Your name is required — this gets logged to the audit trail.")
    else:
        # Only log the sliders that actually moved — logging all three on
        # every save made the audit trail claim R2 changed even on a
        # save that only touched R1.
        for (rule_id, param_name), value in proposed.items():
            if value != float(config[(rule_id, param_name)]):
                set_rule_param(rule_id, param_name, value, admin_name.strip())
        st.success("Saved. The existing (frozen) dataset's alerts are unaffected — this only governs "
                   "future rule evaluation, e.g. through the preview above.")
        st.cache_data.clear()
        st.rerun()
if not changed:
    st.caption("Sliders match the currently saved values — nothing to save.")

st.divider()
with st.expander("Change history for these thresholds"):
    rows = get_audit_log("SYSTEM-RULES")
    if not rows:
        st.caption("No changes recorded yet — these are still the documented defaults.")
    else:
        for row in rows:
            st.write(f"{row['timestamp'][:19].replace('T',' ')} UTC — **{row['actor_name']}** — {row['action']}")

st.divider()
st.caption(
    "Scope note: this changes the CONFIGURED thresholds only. The 40 alerts already in the dataset were "
    "generated once, deterministically, and are not live-recomputed against these settings — that keeps the "
    "frozen C1/C2 demo scenario stable regardless of what an admin adjusts here. Playbook content (the RAG "
    "knowledge base) is viewable/searchable on the Admin Knowledge Base page; editing it there is a documented "
    "next step, not yet built. All data is fictional."
)
