# -*- coding: utf-8 -*-
"""
Admin: Rule Configuration — pending item #3 (F10 in the PRD: "View/adjust
the two trigger rule thresholds").

Not a form that silently saves a number: adjusting a threshold here runs a
live recomputation against the stored fictional transaction data first, so whoever is
changing R1/R2 can see roughly how many more (or fewer) accounts would
trigger before committing to it. The dataset's actual alerts table is never
regenerated by this screen — that stays fixed, so the frozen C1/C2 demo
scenario can never be altered by an admin fat-fingering a threshold.
"""
import os
import streamlit as st

import sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from data.runtime_db import get_rule_config, set_rule_params, get_audit_log
from data.trigger_rules import preview_trigger_counts
from ui_common import require_login, role_warning, page_banner, page_flow, get_admin_passcode

st.set_page_config(page_title="InvestigateIQ — Rule Config", page_icon="⚙️", layout="wide")
user_name, user_role = require_login()

ADMIN_PASSCODE = get_admin_passcode()

page_banner("⚙️", "Admin — Trigger Rule Configuration", "Adjust R1/R2 thresholds and preview the illustrative effect before saving.")
page_flow("Test how threshold changes would affect this fictional dataset", [
    ("Unlock", "Enter the admin passcode."),
    ("Adjust values", "Change the two saved rule thresholds."),
    ("Preview", "See an illustrative count from stored transactions."),
    ("Save", "Persist the settings and an audit event."),
], "This does not regenerate existing alerts or implement a complete bank monitoring engine.")
st.write("")
role_warning(user_role, "Admin")

if "rules_admin_unlocked" not in st.session_state:
    st.session_state.rules_admin_unlocked = False

if not st.session_state.rules_admin_unlocked:
    code = st.text_input(
        "Admin passcode", type="password",
        help="Limited access gate for settings; not production-grade authentication or authorization.",
    )
    if st.button("Unlock", help="Check the passcode and open the threshold preview controls."):
        if code == ADMIN_PASSCODE:
            st.session_state.rules_admin_unlocked = True
            st.rerun()
        else:
            st.error("Incorrect passcode.")
    st.stop()

config = get_rule_config()

st.subheader("Current thresholds (saved)")
c1, c2, c3 = st.columns(3)
c1.metric("R1 — Amount deviation", f"{config[('R1','deviation_multiplier')]}x baseline",
          help="R1 fires when a credit is at least this many times the account's own trailing average — "
               "the first of the two rules behind the fixed C1/C2 comparison cases.")
c2.metric("R2 — Outbound proxy", f"{config[('R2','pass_through_pct')]}% of credit",
          help="Illustrative preview: aggregate debits from the same account are compared with one credit. "
               "This does not prove that the credit funded the debits or that funds crossed two linked hops.")
c3.metric("R2 — Window", f"{config[('R2','window_hours')]} hours",
          help="How long after the flagged credit R2 keeps watching for it to leave again.")

st.divider()
st.subheader("Propose new thresholds")
st.caption(
    "These sliders don't save anything yet. Adjust, then **Preview impact** to see roughly how many accounts "
    "in the fictional dataset would trigger under the new settings — only then decide whether to save."
)

pc1, pc2, pc3 = st.columns(3)
new_dev = pc1.slider("R1: deviation multiplier", 2.0, 10.0, float(config[("R1", "deviation_multiplier")]), 0.5,
                      help="A credit must be at least this many times the account's trailing average to flag R1.")
new_pct = pc2.slider("R2: pass-through %", 30.0, 100.0, float(config[("R2", "pass_through_pct")]), 5.0,
                      help="This much of the flagged credit must leave again within the window to flag R2.")
new_window = pc3.slider("R2: window (hours)", 12.0, 168.0, float(config[("R2", "window_hours")]), 6.0,
                         help="How long after the credit R2 keeps watching for it to leave again.")

proposed = {("R1", "deviation_multiplier"): new_dev, ("R2", "pass_through_pct"): new_pct, ("R2", "window_hours"): new_window}
changed = proposed != {k: float(v) for k, v in config.items()}

if st.button("🔍 Preview impact on the fictional dataset", type="secondary",
             help="Recomputes R1/R2 against stored fictional account transaction history using the sliders "
                  "above — read-only, nothing is saved by clicking this."):
    with st.spinner("Recomputing R1/R2 against fictional transaction history..."):
        result = preview_trigger_counts(proposed, sample_limit=300)
    st.session_state["rule_preview"] = result

if "rule_preview" in st.session_state:
    r = st.session_state["rule_preview"]
    st.markdown("**Preview result** (sample of up to 300 accounts, fictional transaction data):")
    pc1, pc2, pc3 = st.columns(3)
    pc1.metric("Accounts checked", r["accounts_checked"],
               help="Number of fictional accounts sampled for this preview, up to 300.")
    pc2.metric("Would meet R1", r["r1_only_count"],
               help="Sampled accounts matching the proposed amount-deviation condition.")
    pc3.metric("R1 + outbound proxy", r["r1_and_r2_count"],
               help="Sampled accounts matching both preview conditions; not verified alerts or linked-hop tracing.")
    if r["examples"]:
        st.error(
            f"🔴 {r['r1_and_r2_count']} sampled account(s) meet both proposed review conditions. "
            "Red marks a review signal, not confirmed laundering or a verified money trail."
        )
        st.caption("Example accounts matching both preview conditions; not validated alerts:")
        st.dataframe(r["examples"], hide_index=True, use_container_width=True)
    else:
        st.caption("No accounts in this sample matched both preview conditions.")
    st.info("This is a sensitivity preview, not a full trigger engine. It does not trace linked transfer hops "
            "or create/recalculate alerts. Existing alerts are fixed fictional examples.")

st.divider()
st.subheader("Save")
admin_name = st.text_input(
    "Your name (for the audit trail)", value=user_name,
    help="Every threshold change is written to the audit log below with this name attached — required, "
         "can't be blank.",
)
if st.button("💾 Save these thresholds", type="primary", disabled=not changed,
             help="Saves the sliders above as the new configured thresholds. Disabled until you change at "
                  "least one slider from its currently saved value. Does not touch the existing dataset's "
                  "alerts — see the scope note below."):
    if not admin_name.strip():
        st.error("Your name is required — this gets logged to the audit trail.")
    else:
        # Only log the sliders that actually moved — logging all three on
        # every save made the audit trail claim R2 changed even on a
        # save that only touched R1.
        moved = {key: value for key, value in proposed.items() if value != float(config[key])}
        try:
            set_rule_params(moved, admin_name.strip())
        except Exception as error:
            st.error(f"Could not save the threshold batch; no partial change was applied: {error}")
        else:
            st.success("Saved as one audited batch. The existing fictional alerts are unaffected; "
                       "these values only affect future sensitivity previews.")
            st.cache_data.clear()
            st.rerun()
if not changed:
    st.caption("Sliders match the currently saved values — nothing to save.")

st.divider()
with st.expander("Change history for these thresholds"):
    rows = get_audit_log("SYSTEM-RULES")
    if not rows:
        st.caption("No changes recorded yet — these are still the documented defaults.")
    else:
        for row in rows:
            st.write(f"{row['timestamp'][:19].replace('T',' ')} UTC — **{row['actor_name']}** — {row['action']}")

st.divider()
st.caption(
    "Scope note: this changes the CONFIGURED preview thresholds only. The queue has 42 imported workbook alerts "
    "and two test alerts calculated when the database was built; none is live-recomputed from these saved settings. "
    "The read-only Rule Lab on Evidence & RAG separately recalculates a fictional ten-row batch using fixed "
    "5x/80%/three-beneficiary conditions. Playbook content (the RAG "
    "knowledge base) is viewable/searchable on the Admin Knowledge Base page; editing it there is a documented "
    "next step, not yet built. All data is fictional."
)
