# -*- coding: utf-8 -*-
"""
Admin: Rule Configuration — pending item #3 (F10 in the PRD: "View/adjust
the two trigger rule thresholds").

Not a form that silently saves a number: adjusting a threshold here runs a
live recomputation against the real transaction data first, so whoever is
changing R1/R2 can see roughly how many more (or fewer) accounts would
trigger before committing to it. The dataset's actual alerts table is never
regenerated by this screen — that stays fixed, so the frozen C1/C2 demo
scenario can never be altered by an admin fat-fingering a threshold.
"""
import os
import streamlit as st

import sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from data.runtime_db import get_rule_config, set_rule_param, get_audit_log
from data.trigger_rules import preview_trigger_counts
from ui_common import require_login, role_warning

st.set_page_config(page_title="InvestigateIQ — Rule Config", page_icon="⚙️", layout="wide")
user_name, user_role = require_login()

ADMIN_PASSCODE = os.environ.get("ADMIN_PASSCODE", "investigateiq-admin")

st.markdown(
    """
    <style>
    .iq-banner { background-color: #1A2A4A; color: white; padding: 14px 22px; border-radius: 10px; }
    .iq-banner h1 { margin: 0; font-size: 22px; }
    .iq-banner p { margin: 2px 0 0 0; color: #C9D6E8; font-size: 13px; }
    </style>
    <div class="iq-banner">
        <h1>⚙️ Admin — Trigger Rule Configuration</h1>
        <p>Adjust R1/R2 thresholds and preview the real effect before saving.</p>
    </div>
    """,
    unsafe_allow_html=True,
)
st.write("")
role_warning(user_role, "Admin")

if "rules_admin_unlocked" not in st.session_state:
    st.session_state.rules_admin_unlocked = False

if not st.session_state.rules_admin_unlocked:
    code = st.text_input("Admin passcode", type="password")
    if st.button("Unlock"):
        if code == ADMIN_PASSCODE:
            st.session_state.rules_admin_unlocked = True
            st.rerun()
        else:
            st.error("Incorrect passcode.")
    st.stop()

config = get_rule_config()

st.subheader("Current thresholds (saved)")
c1, c2, c3 = st.columns(3)
c1.metric("R1 — Amount deviation", f"{config[('R1','deviation_multiplier')]}x baseline")
c2.metric("R2 — Pass-through", f"{config[('R2','pass_through_pct')]}% of credit")
c3.metric("R2 — Window", f"{config[('R2','window_hours')]} hours")

st.divider()
st.subheader("Propose new thresholds")
st.caption(
    "These sliders don't save anything yet. Adjust, then **Preview impact** to see roughly how many accounts "
    "in the real dataset would trigger under the new settings — only then decide whether to save."
)

pc1, pc2, pc3 = st.columns(3)
new_dev = pc1.slider("R1: deviation multiplier", 2.0, 10.0, float(config[("R1", "deviation_multiplier")]), 0.5,
                      help="A credit must be at least this many times the account's trailing average to flag R1.")
new_pct = pc2.slider("R2: pass-through %", 30.0, 100.0, float(config[("R2", "pass_through_pct")]), 5.0,
                      help="This much of the flagged credit must leave again within the window to flag R2.")
new_window = pc3.slider("R2: window (hours)", 12.0, 168.0, float(config[("R2", "window_hours")]), 6.0,
                         help="How long after the credit R2 keeps watching for it to leave again.")

proposed = {("R1", "deviation_multiplier"): new_dev, ("R2", "pass_through_pct"): new_pct, ("R2", "window_hours"): new_window}
changed = proposed != {k: float(v) for k, v in config.items()}

if st.button("🔍 Preview impact on the real dataset", type="secondary"):
    with st.spinner("Recomputing R1/R2 against real transaction history..."):
        result = preview_trigger_counts(proposed, sample_limit=300)
    st.session_state["rule_preview"] = result

if "rule_preview" in st.session_state:
    r = st.session_state["rule_preview"]
    st.markdown("**Preview result** (sample of up to 300 accounts, real transaction data):")
    pc1, pc2, pc3 = st.columns(3)
    pc1.metric("Accounts checked", r["accounts_checked"])
    pc2.metric("Would meet R1", r["r1_only_count"])
    pc3.metric("Would meet R1 + R2 (full alert)", r["r1_and_r2_count"])
    if r["examples"]:
        st.caption("Example accounts that would trigger both rules under these settings:")
        st.dataframe(r["examples"], hide_index=True, use_container_width=True)
    else:
        st.caption("No accounts in this sample would meet both rules under these settings.")

st.divider()
st.subheader("Save")
admin_name = st.text_input("Your name (for the audit trail)", value=user_name)
if st.button("💾 Save these thresholds", type="primary", disabled=not changed):
    if not admin_name.strip():
        st.error("Your name is required — this gets logged to the audit trail.")
    else:
        set_rule_param("R1", "deviation_multiplier", new_dev, admin_name.strip())
        set_rule_param("R2", "pass_through_pct", new_pct, admin_name.strip())
        set_rule_param("R2", "window_hours", new_window, admin_name.strip())
        st.success("Saved. The existing (frozen) dataset's alerts are unaffected — this only governs "
                   "future rule evaluation, e.g. through the preview above.")
        st.cache_data.clear()
        st.rerun()
if not changed:
    st.caption("Sliders match the currently saved values — nothing to save.")

st.divider()
with st.expander("Change history for these thresholds"):
    rows = get_audit_log("SYSTEM-RULES")
    if not rows:
        st.caption("No changes recorded yet — these are still the documented defaults.")
    else:
        for row in rows:
            st.write(f"{row['timestamp'][:19].replace('T',' ')} UTC — **{row['actor_name']}** — {row['action']}")

st.divider()
st.caption(
    "Scope note: this changes the CONFIGURED thresholds only. The 40 alerts already in the dataset were "
    "generated once, deterministically, and are not live-recomputed against these settings — that keeps the "
    "frozen C1/C2 demo scenario stable regardless of what an admin adjusts here. Playbook content (the RAG "
    "knowledge base) is viewable/searchable on the Admin Knowledge Base page; editing it there is a documented "
    "next step, not yet built. All data is fictional."
)
